version: 1
handlers:
  console:
    class: logging.StreamHandler
    stream  : ext://sys.stdout
    formatter: default
  file:
    class: logging.FileHandler
    filename: 'file.log'
    formatter: brief
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(filename)-35s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
root:
  level: INFO
  handlers: [ console ]
loggers:
  __main__:
    level: INFO
    handlers: [ console ]
    propagate: False
  tensorflow:
    level: ERROR
    handlers: [ console ]
    propagate: False
  matplotlib.category:
    level: WARNING
    handlers: [ console ]
    propagate: False
  file_logger:
    level: INFO
    handlers: [ file ]
    propagate: False